### ISSUE TITLE
Spawn git Enoent

### ISSUE THREAD

**Issue by vasanththangavel** [w3cj/express-api-starter#1]
Am getting error while try to install **npx create-express-api server** in nodejs to create the folder, it shows spawn git ENOENT error
![enoent](https://user-images.githubusercontent.com/46041430/50326611-4d3df600-0511-11e9-9199-b5e1d97aacb1.JPG)

**Comment by w3cj** [comment]
Hey @vasanththangavel the `create-express-api` cli tool requires git. Make sure you have git installed before running the command.

Also, I have only tested this on mac / linux.

**Comment by vasanththangavel** [comment]
Thanks @w3cj For your Kind reply but again i still got error.

**Comment by w3cj** [comment]
Might be an issue with spawning commands in Windows. I'll leave this issue open so I will remember to look into it on a Windows machine.

**Comment by vasanththangavel** [comment]
For windows directly installing showing error ,but after cloning separately and run the npm install command to install the dependencis, it worked. Thanks @w3cj

**Comment by yash0xdev** [comment]
@vasanththangavel  can you tell me how you cloned it separately.

**Comment by vasanththangavel** [comment]
@loserhim please download the express-api directly from github using this link https://github.com/w3cj/create-express-api.git. extract & open cmd from this directory and run npm install command to install this dependencies then continue with your workflow.

**Comment by Marlond25** [comment]
I solved this on windows 10 by updating the nodemon package.

**Comment by Nikita711** [comment]
@vasanththangavel  I'm facing the same issue even after cloning them separately can you please write in detail what exactly is  needed to done .

**Comment by vasanththangavel** [comment]
@Nikita711 after cloning the repo, cd to the cloned repo and open the cmd run npm install it will automatically install all dependencies in the package.json. if u still facing the same error ,update with screenshot.

**Comment by majerlazor** [comment]
Hello. I'm still getting an error after cloning and install. Here is the screenshot of the error:

![1](https://user-images.githubusercontent.com/75080934/110066576-c4879980-7dac-11eb-9542-4b467f94f0a7.png)

I first cloned the repo into my project folder, "JS", using git bash. I then I cd into the create-express-api folder and ran npm install in the same bash terminal. After that, I cd out of the create-express-api folder and ran npx create-express-api server0.

What did I do wrong? Your help would be greatly appreciated. I'm on Windows 10 btw.

**Comment by Nikita711** [comment]
after cloning the repo, cd to the cloned repo and open the cmd run npm
install it will automatically install all dependencies in the
package.json.I think this should help as I did the same .
