### ISSUE TITLE
Error:npx create-express-api server

### ISSUE THREAD

**Issue by vasanththangavel** [w3cj/express-api-starter#2]
@w3cj After installing Git on my system, i tried the code **npx create-express-api server** ,now it's cloned the express api starter while trying to install dependencies it again shows error and also i tried directly to clone with git bash, it's cloned, but while runing the code **npm run dev** again got error.
Error while running code:**npx create-express-api server** 
![error](https://user-images.githubusercontent.com/46041430/50952004-1ab26800-14d5-11e9-99c0-de66877e0504.JPG)
Error while directly Clone using Git bash
![error1](https://user-images.githubusercontent.com/46041430/50952006-1b4afe80-14d5-11e9-8494-a03d159bd0d7.JPG)

**Comment by w3cj** [comment]
After cloning the repo, you need to run `npm install` before running `npm run dev`

**Comment by vasanththangavel** [comment]
Thanks @w3cj , it works, now i can able to access the server.
